trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: 'my-static-website-demo'
  resourceGroup: 'StaticWebsiteRG'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "No build needed for static website"
      displayName: 'Build Step'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployJob
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '<YourServiceConnection>'
              appName: '$(webAppName)'
              package: '$(System.DefaultWorkingDirectory)'

