trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Environment (Optional)'

- script: |
    echo "Building simple static website project"
    mkdir -p output
    cp -r * output
  displayName: 'Build static site'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'output'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'

